wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_2.pkl
epochs:
  value: 10
learning_rate:
  value: 0.0027178654358950183
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 456
