wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_2.pkl
epochs:
  value: 5
learning_rate:
  value: 0.0020186829962366244
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 42
