wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_1.pkl
epochs:
  value: 5
learning_rate:
  value: 0.009144985731219926
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 42
