wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746011369
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 14
      - 23
      - 24
      - 37
      4: 3.13.2
      5: 0.19.8
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 128
data_type:
  desc: null
  value: train_s_n_2.pkl
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.0012150166707620834
model_modul_name:
  desc: null
  value:
  - NN_models
  - NN_model1
optimizer_name:
  desc: null
  value: Adam
seed:
  desc: null
  value: 42
