wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_q_1.pkl
epochs:
  value: 10
learning_rate:
  value: 0.009322542920711451
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 123
