wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_n_1.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.003420257110895288
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: SGD
seed:
  value: 42
