wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_n_1.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.008337168193146812
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: SGD
seed:
  value: 42
