wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_s_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.003777765503739729
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: SGD
seed:
  value: 42
