wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_s_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.006999117035479339
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 42
