wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.006202691716674345
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 42
