wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.005129326678823779
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: LBFGS
seed:
  value: 42
