wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.006835552874402814
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: LBFGS
seed:
  value: 42
