wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_c_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.008296113914210751
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: Adam
seed:
  value: 42
