wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.001614892480287674
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: LBFGS
seed:
  value: 42
