wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.001033967488667246
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: LBFGS
seed:
  value: 42
