wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_c_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.006242186059779799
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: Adam
seed:
  value: 42
