wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.009010179312186006
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: Adam
seed:
  value: 42
