wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.003165438838988468
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: Adam
seed:
  value: 42
