wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.005399156739238125
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: LBFGS
seed:
  value: 42
