wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.008094649595309231
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: LBFGS
seed:
  value: 42
