wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.009367612448248276
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: LBFGS
seed:
  value: 42
