wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.0039628915999405994
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 42
