wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.01
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: SGD
seed:
  value: 42
