wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_2.pkl
epochs:
  value: 3
learning_rate:
  value: 0.0020401131326906945
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 456
