wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_1.pkl
epochs:
  value: 10
learning_rate:
  value: 0.008391039307686997
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 42
