wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_1.pkl
epochs:
  value: 3
learning_rate:
  value: 0.0054794999814255126
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 456
