wandb_version: 1

batch_size:
  value: 64
data_type:
  value: train_q_1.pkl
epochs:
  value: 10
learning_rate:
  value: 0.006184237935052191
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 456
