wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_1.pkl
epochs:
  value: 5
learning_rate:
  value: 0.008500026225771723
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 456
