wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_1.pkl
epochs:
  value: 3
learning_rate:
  value: 0.0014663894127918368
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 123
