wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_1.pkl
epochs:
  value: 10
learning_rate:
  value: 0.005144244734257723
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 123
