wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_1
epochs:
  value: 1000
learning_rate:
  value: 0.005523332702944231
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: BFGS
seed:
  value: 123
