name: fagproject
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - deprecated=1.2.13
  - et_xmlfile=1.1.0
  - expat=2.6.4
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.4
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.0.16
  - opentelemetry-api=1.26.0
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.5.1
  - pytz=2024.1
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - wrapt=1.17.0
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - docker-pycreds==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - smmap==5.0.2
      - urllib3==2.3.0
      - wandb==0.19.8
