wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.007405383153347564
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: BFGS
seed:
  value: 456
