wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.006970198002406556
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizr:
  value: Adam
seed:
  value: 42
