wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_n_1.pkk
epochs:
  value: 1500
learning_rate:
  value: 0.0020587637947266767
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizr:
  value: BFGS
seed:
  value: 123
