wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_1.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.009639586997354128
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizr:
  value: Adam
seed:
  value: 123
