wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.005065658685787147
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 456
