wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_n_1.pkk
epochs:
  value: 2000
learning_rate:
  value: 0.0031722058653892355
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 123
