wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_2.pkl
epochs:
  value: 3
learning_rate:
  value: 0.008877063056150826
model_modul_name:
  value:
  - NN_models
  - NN_model1
seed:
  value: 42
