wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_1.pkl
epochs:
  value: 10
learning_rate:
  value: 0.003105928333249352
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 123
