wandb_version: 1

batch_size:
  value: 128
data_type:
  value: train_q_1.pkl
epochs:
  value: 3
learning_rate:
  value: 0.0068254600811255665
model_modul_name:
  value:
  - PN_model2
  - Polynomial_Network
seed:
  value: 123
