wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.007486220759591896
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: Adam
seed:
  value: 456
