wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_2.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.007811964598176351
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: SGD
seed:
  value: 456
