wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 1000
learning_rate:
  value: 0.006301684233791614
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: Adam
seed:
  value: 123
