wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_1.pkl
epochs:
  value: 1500
learning_rate:
  value: 0.004773412550957375
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: BFGS
seed:
  value: 42
