wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_q_n_2.pkl
epochs:
  value: 1500
learning_rate:
  value: 0.0028015856445492314
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: SGD
seed:
  value: 123
