wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 1500
learning_rate:
  value: 0.003627722819940579
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: BFGS
seed:
  value: 123
