wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.009997491777320344
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: BFGS
seed:
  value: 456
