wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_s_n_2.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.004874200416265951
model_modul_name:
  value:
  - PN_models
  - Polynomial_Network
optimizer_name:
  value: SGD
seed:
  value: 456
