wandb_version: 1

batch_size:
  value: 32
data_type:
  value: train_c_n_1.pkl
epochs:
  value: 2000
learning_rate:
  value: 0.0092709244310915
model_modul_name:
  value:
  - NN_models
  - NN_model1
optimizer_name:
  value: BFGS
seed:
  value: 456
